name: Build APK
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install flet
      - run: sudo apt-get update && sudo apt-get install -y ninja-build
      - run: yes | flet build apk --output ./prank.apk
      - uses: actions/upload-artifact@v4
        with:
          name: my-prank-apk
          path: ./prank.apk
